name: 将main.py打包成EXE文件
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: try to install python
        uses: actions/setup-python@v3
      #- name: try use ffmpeg
        #uses: FedericoCarboni/setup-ffmpeg@v1
      - name: try to install python library
        #run : python -m pip install requests ffmpeg-python
        run : python -m pip install pyinstaller
      - name : "Try to run python file"
        run : python -m pyinstaller -F ${{ github.workspace }}/main.py
      - name : "move exe file"
        run : cp ${{ github.workspace }}/dist/main.exe ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."